// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zououhirrfjjqfspfviv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvdW91aGlycmZqanFmc3Bmdml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDk1MDIsImV4cCI6MjA1MzIyNTUwMn0.Y8PzmWYzY-AS0AYUO3FYOTkSG3ChBibd5TgqZBt7dQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);